apiVersion: v1
kind: Secret
metadata:
  name: expenses-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  url: 'https://raw.githubusercontent.com/hasAnybodySeenHarry/debt-tracker/main/charts'