service:
  type: ClusterIP
  port: 8080
  internalPort: 4000

db:
  dsn: cG9zdGdyZXM6Ly9oYXJyeTpwYXNzd29yZEBsb2NhbGhvc3Q6NTQzMi9leHBlbnNlcz9zc2xtb2RlPWRpc2FibGU=
  maxOpenConn: MzA=
  maxIdleConn: MzA=

replicaCount: 1

image:
  registry: docker.io
  repository: "demona9458/expenses"
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

serviceAccountName: default

deploymentAnnotations: {}
podAnnotations: {}

podSecurityContext: {}

serviceAccount:
  create: false
  name: ""

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  privileged: false
  readOnlyRootFilesystem: false
  runAsGroup: 1001
  runAsNoRoot: true
  runAsUser: 1001

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

livenessProbe:
  path: /v1/healthcheck
  port: 4000

readinessProbe:
  path: /v1/healthcheck
  port: 4000

startupProbe:
  path: /v1/healthcheck
  port: 4000

topologySpreadConstraints: []

extraEnv: []

podDisruptionBudget:
  enabled: false
  minAvailable: 1
  maxUnavailable: ""

env:
- name: dsn
  valueFrom:
    secretKeyRef:
      name: db-secrets
      key: dsn
- name: max-open-conn
  valueFrom:
    secretKeyRef:
      name: db-secrets
      key: maxOpenConn
- name: max-idle-conn
  valueFrom:
    secretKeyRef:
      name: db-secrets
      key: maxIdleConn