service:
  type: ClusterIP
  port: 8080
  internalPort: 8080
  grpcPort: 50051

db:
  host: postgres-database
  username: harry
  password: password
  database: expenses
  port: 5432
  maxOpenConn: 30
  maxIdleConn: 30

rabbitmq:
  username: harry
  password: password
  host: rabbitmq-proxy
  port: 5672

pubsub:
  host: kafka-node
  port: 9092

replicaCount: 1

image:
  registry: docker.io
  repository: "demona9458/expenses"
  tag: "latest"
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

serviceAccountName: default

deploymentAnnotations: {}
podAnnotations: {}

podSecurityContext: {}

serviceAccount:
  create: false
  name: ""

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  privileged: false
  readOnlyRootFilesystem: false
  runAsGroup: 1001
  runAsNonRoot: true
  runAsUser: 1001

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

livenessProbe:
  path: /v1/healthcheck
  port: 8080

readinessProbe:
  path: /v1/healthcheck
  port: 8080

startupProbe:
  path: /v1/healthcheck
  port: 8080

topologySpreadConstraints: []

extraEnv: []

podDisruptionBudget:
  enabled: false
  minAvailable: 1
  maxUnavailable: ""

env:
- name: GRPC_PORT
  value: "50051"
- name: PORT
  value: "8080"
- name: DB_USERNAME
  valueFrom:
    secretKeyRef:
      name: db-secrets
      key: username
- name: DB_PASSWORD
  valueFrom:
    secretKeyRef:
      name: db-secrets
      key: password
- name: DB_PORT
  valueFrom:
    secretKeyRef:
      name: db-secrets
      key: port
- name: MAX_OPEN_CONN
  valueFrom:
    secretKeyRef:
      name: db-secrets
      key: maxOpenConn
- name: MAX_IDLE_CONN
  valueFrom:
    secretKeyRef:
      name: db-secrets
      key: maxIdleConn
- name: AMQP_USERNAME
  valueFrom:
    secretKeyRef:
      name: rabbitmq-secrets
      key: username
- name: AMQP_PASSWORD
  valueFrom:
    secretKeyRef:
      name: rabbitmq-secrets
      key: password
- name: AMQP_HOST
  valueFrom:
    secretKeyRef:
      name: rabbitmq-secrets
      key: host
- name: AMQP_PORT
  valueFrom:
    secretKeyRef:
      name: rabbitmq-secrets
      key: port
- name: PUB_HOST
  valueFrom:
    secretKeyRef:
      name: pubsub-secrets
      key: host
- name: PUB_PORT
  valueFrom:
    secretKeyRef:
      name: pubsub-secrets
      key: port