service:
  type: ClusterIP
  port: 8080
  internalPort: 8080
  grpcPort: 50051

db:
  dsn: postgres://harry:password@postgres-database:5432/expenses?sslmode=disable
  maxOpenConn: 30
  maxIdleConn: 30

rabbitmq:
  uri: amqp://harry:password@rabbitmq:5672/

replicaCount: 1

image:
  registry: docker.io
  repository: "demona9458/expenses"
  tag: "latest"
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

serviceAccountName: default

deploymentAnnotations: {}
podAnnotations: {}

podSecurityContext: {}

serviceAccount:
  create: false
  name: ""

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  privileged: false
  readOnlyRootFilesystem: false
  runAsGroup: 1001
  runAsNonRoot: true
  runAsUser: 1001

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

livenessProbe:
  path: /v1/healthcheck
  port: 4000

readinessProbe:
  path: /v1/healthcheck
  port: 4000

startupProbe:
  path: /v1/healthcheck
  port: 4000

topologySpreadConstraints: []

extraEnv: []

podDisruptionBudget:
  enabled: false
  minAvailable: 1
  maxUnavailable: ""

env:
- name: TCP
  value: "50051"
- name: PORT
  value: "8080"
- name: DSN
  valueFrom:
    secretKeyRef:
      name: db-secrets
      key: dsn
- name: MAX-OPEN-CONN
  valueFrom:
    secretKeyRef:
      name: db-secrets
      key: maxOpenConn
- name: MAX-IDLE-CONN
  valueFrom:
    secretKeyRef:
      name: db-secrets
      key: maxIdleConn
- name: AMQP_URI
  valueFrom:
    secretKeyRef:
      name: rabbitmq-secrets
      key: uri