apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-setup-script
data:
  setup-postgres.sh: |
    #!/bin/sh
    set -e

    # Install necessary tools
    echo "Installing necessary tools..."
    apk add --no-cache git wget postgresql-client

    # Install go-migrate
    echo "Installing go-migrate..."
    wget https://github.com/golang-migrate/migrate/releases/download/v4.14.1/migrate.linux-amd64.tar.gz
    tar -xzf migrate.linux-amd64.tar.gz
    mv migrate.linux-amd64 /usr/local/bin/migrate

    # Wait for PostgreSQL to be ready
    echo "Waiting for PostgreSQL to be ready..."
    until psql -h postgres-database -U harry -d expenses -c '\q'; do
      sleep 2
    done

    echo "PostgreSQL is ready."

    # Install extensions
    echo "Installing extensions..."
    psql -h postgres-database -U harry -d expenses <<EOF
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
    CREATE EXTENSION IF NOT EXISTS "citext";
    EOF

    echo "Extensions installed."

    # Clone the repository
    echo "Cloning repository for migrations..."
    git clone https://github.com/hasAnybodySeenHarry/debt-tracker.git /migrations

    # Run migrations
    echo "Running migrations..."
    migrate -path /migrations/migrations -database postgres://harry:password@postgres-database:5432/expenses up

    echo "Migrations applied."
