apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-setup-job
spec:
  template:
    spec:
      containers:
      - name: setup
        image: alpine:latest
        env:
        - name: PGPASSWORD
          value: "password"
        command:
        - /bin/sh
        - -c
        - |
          echo "Installing necessary tools..."
          apk add --no-cache git wget postgresql-client

          echo "Installing go-migrate..."
          wget https://github.com/golang-migrate/migrate/releases/download/v4.14.1/migrate.linux-amd64.tar.gz
          tar -xzf migrate.linux-amd64.tar.gz
          mv migrate.linux-amd64 /usr/local/bin/migrate

          echo "Waiting for PostgreSQL to be ready..."
          until psql -h postgres-database -U harry -d expenses -c '\q'; do
            sleep 2
          done

          echo "PostgreSQL is ready."

          echo "Installing extensions..."
          psql -h postgres-database -U harry -d expenses <<EOF
          CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
          CREATE EXTENSION IF NOT EXISTS "citext";
          EOF

          echo "Extensions installed."

          echo "Cloning repository for migrations..."
          git clone https://github.com/hasAnybodySeenHarry/debt-tracker.git /migrations

          echo "Running migrations..."
          migrate -path /migrations/migrations -database postgres://harry:password@postgres-database:5432/expenses?sslmode=disable up

          echo "Migrations applied."
      restartPolicy: Never
