apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: redis
spec:
  containers:
  - name: redis
    image: redis:alpine
    command: ["redis-server", "--requirepass", "password"]
    ports:
    - containerPort: 6379
    env:
    - name: REDIS_PASSWORD
      value: "password"
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
