kind: Ingress
metadata:
  name: expenses-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: development-expenses
            port:
              number: 8080
        path: /
        pathType: Prefix