apiVersion: v1
kind: Pod
metadata:
  name: kafka-node
  labels:
    app: kafka
spec:
  containers:
  - name: kafka
    image: bitnami/kafka:latest
    env:
    - name: KAFKA_ZOOKEEPER_CONNECT
      value: zookeeper-node:2181
    - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
      value: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
    - name: KAFKA_LISTENERS
      value: INSIDE://0.0.0.0:9092,OUTSIDE://localhost:9093
    - name: KAFKA_LISTENER_NAME
      value: INSIDE
    - name: KAFKA_ADVERTISED_LISTENERS
      value: INSIDE://kafka-node:9092,OUTSIDE://localhost:9093
    - name: KAFKA_INTER_BROKER_LISTENER_NAME
      value: INSIDE
    ports:
    - containerPort: 9092
    - containerPort: 9093
  volumeMounts:
  - name: kafka-data
    mountPath: /bitnami/kafka
  volumes:
  - name: kafka-data
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-node
spec:
  ports:
  - port: 9092
    targetPort: 9092
  - port: 9093
    targetPort: 9093
  selector:
    app: kafka
