apiVersion: v1
kind: Pod
metadata:
  name: zookeeper-node
  labels:
    app: zookeeper
spec:
  containers:
  - name: zookeeper
    image: bitnami/zookeeper:latest
    env:
    - name: ZOOKEEPER_CLIENT_PORT
      value: "2181"
    - name: ALLOW_ANONYMOUS_LOGIN
      value: "yes"
    ports:
    - containerPort: 2181
    volumeMounts:
    - name: zookeeper-data
      mountPath: /bitnami/zookeeper
  volumes:
  - name: zookeeper-data
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-node
spec:
  ports:
  - port: 2181
    targetPort: 2181
  selector:
    app: zookeeper