apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secrets
type: Opaque
data:
  username: {{ .Values.rabbitmq.username | b64enc }}
  password: {{ .Values.rabbitmq.password | b64enc }}
  host: {{ .Values.rabbitmq.host | b64enc }}
  port: {{ .Values.rabbitmq.port | toString | b64enc }}
