apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  dsn: {{ .Values.db.dsn | b64enc }}
  maxOpenConn: {{ .Values.db.maxOpenConn | toString | b64enc }}
  maxIdleConn: {{ .Values.db.maxOpenConn | toString | b64enc }}