apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  dsn: {{ .Values.db.dsn | quote }}
  maxOpenConn: {{ .Values.db.maxOpenConn | quote }}
  maxIdleConn: {{ .Values.db.maxOpenConn | quote }}