name: Issue Labeler
on:
  issues:
    types: [opened]
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
    - name: Label new issues
      uses: github/issue-labeler@v3.3
      with:
        configuration-path: .github/labeler.yaml
        enable-versioned-regex: 0
        repo-token: ${{ github.token }}
